### ISSUE TITLE
Vintageous inserts text behind cursor location when a plugin's command line is accessed via the Sublime command palette

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#47]
<a href="https://github.com/amclain"><img src="https://avatars2.githubusercontent.com/u/4755047?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amclain](https://github.com/amclain)**
_Monday May 26, 2014 at 23:05 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/617_

----

When a plugin's command line is opened via the Sublime command palette, Vintageous reverts to normal mode. This causes text insertion commands to insert the text behind the cursor location. I've confirmed this problem with both [Text Pastry](https://github.com/duydao/Text-Pastry) and [InsertDate](https://github.com/FichteFoll/sublimetext-insertdate).

In [Text Pastry](https://github.com/duydao/Text-Pastry), position multiple cursors in `insert` mode (illustrated with `|`) just before the semicolon, just as you would if you were to start typing more text.

``` text
constant_1 = |;
constant_2 = |;
constant_3 = |;
constant_4 = |;
```

Open Sublime's command palette via `ctrl + shift + p`, select `Text Pastry: Command Line`, and enter `\i101`. The inserted numbers end up behind the cursor location, and the editor reverts to normal mode.

``` text
constant_1 =101 ;
constant_2 =102 ;
constant_3 =103 ;
constant_4 =104 ;
```

See [Text Pastry issue #16](https://github.com/duydao/Text-Pastry/issues/16) for more details.

If the plugin's command line is NOT opened through the Sublime command palette (`ctrl + shift + n`), the operation behaves as expected. Likewise, an insert text operation like `Text Pastry: From 1 To X` executed through the Sublime command palette that does NOT open the plugin's command line behaves as expected.

The [InsertDate](https://github.com/FichteFoll/sublimetext-insertdate) plugin behaves the same way with Vintageous:

``` text
date = |;
```

Open Sublime's command palette via `ctrl + shift + p`, select `InsertDate: Custom`, and enter `%Y-%m-%d`. The inserted numbers end up behind the cursor location, and the editor reverts to normal mode.

``` text
date =2014-05-26 ;
```

Sublime Text 3 build 3059, Win7/Linux.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Tuesday May 27, 2014 at 05:21 GMT_

----

Thanks for the detailed bug report. Unfortunately Vintageous does not support external plugins at the moment. I would be nice if it was smarter about these things, though.

**Comment by gerardroche** [comment]
<a href="https://github.com/duydao"><img src="https://avatars0.githubusercontent.com/u/1011201?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [duydao](https://github.com/duydao)**
_Friday Jun 13, 2014 at 14:21 GMT_

----

@guillermooo vintageous is using a timer to check if the current view lost focus ([xsupport, lines 56-58](https://github.com/guillermooo/Vintageous/blob/7fc41b754726c41e7b313e7408eb5126982940b3/xsupport.py#L56-L58)). If so, vintageous will go back to normal mode.

IMO, an option to enable/disable this behaviour would resolve this issue

**Comment by gerardroche** [comment]
<a href="https://github.com/rahiyer"><img src="https://avatars2.githubusercontent.com/u/204060?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rahiyer](https://github.com/rahiyer)**
_Friday Apr 10, 2015 at 03:56 GMT_

----

The problem is also seen in visual mode. 

For example: if I select a few lines using 'shift + v' and then run "Git: Blame" (using the Git package), it gives the 'blame' for the whole file instead of just the selection, since the selection is lost when Vintageous goes to normal mode. If I repeat the same, but perform the selection using shift + arrow keys (or select using mouse), then the 'blame' is returned only for selected lines.

**Comment by gerardroche** [comment]
Fixed by https://github.com/NeoVintageous/NeoVintageous/issues/273 for the next release 1.6.0.

**Comment by gerardroche** [comment]
@amclain @duydao @rahiyer This has been fixed in NeoVintageous 1.6.0 (NeoVintageous is a fork of the discontinued Vintageous plugin).

**Comment by gerardroche** [comment]
@amclain @duydao @rahiyer It's also possible to create complex mappings. See `:help neovintageous` for details, also https://blog.gerardroche.com/2018/02/21/neovintageous-1.5.0-released/ and https://blog.gerardroche.com/2017/11/01/neovintageous-1.4.0-released/. I'll be preparing a blog post for the additional features in 1.6.0 shortly.

**Comment by amclain** [comment]
Thanks for the work, but this still appears to be broken in NeoVintageous when inserting at the end of a line. This is working with Vintageous.

[Screen Capture Of Issue](https://cl.ly/1m2U272k2T0y)

**Comment by gerardroche** [comment]
I think it may be related to https://github.com/NeoVintageous/NeoVintageous/issues/291

**Comment by gerardroche** [comment]
This should fix it. More info here: https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346

**Comment by amclain** [comment]
:+1: Thanks, that fixed it!
